'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.2032
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Data
Imports System.Runtime.Serialization
Imports System.Xml


<Serializable(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Diagnostics.DebuggerStepThrough(),  _
 System.ComponentModel.ToolboxItem(true)>  _
Public Class dsProdAgeMetric
    Inherits DataSet
    
    Private tabledsProdAgeMetric As dsProdAgeMetricDataTable
    
    Public Sub New()
        MyBase.New
        Me.InitClass
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    Protected Sub New(ByVal info As SerializationInfo, ByVal context As StreamingContext)
        MyBase.New
        Dim strSchema As String = CType(info.GetValue("XmlSchema", GetType(System.String)),String)
        If (Not (strSchema) Is Nothing) Then
            Dim ds As DataSet = New DataSet
            ds.ReadXmlSchema(New XmlTextReader(New System.IO.StringReader(strSchema)))
            If (Not (ds.Tables("dsProdAgeMetric")) Is Nothing) Then
                Me.Tables.Add(New dsProdAgeMetricDataTable(ds.Tables("dsProdAgeMetric")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.InitClass
        End If
        Me.GetSerializationData(info, context)
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    <System.ComponentModel.Browsable(false),  _
     System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)>  _
    Public ReadOnly Property dsProdAgeMetric As dsProdAgeMetricDataTable
        Get
            Return Me.tabledsProdAgeMetric
        End Get
    End Property
    
    Public Overrides Function Clone() As DataSet
        Dim cln As dsProdAgeMetric = CType(MyBase.Clone,dsProdAgeMetric)
        cln.InitVars
        Return cln
    End Function
    
    Protected Overrides Function ShouldSerializeTables() As Boolean
        Return false
    End Function
    
    Protected Overrides Function ShouldSerializeRelations() As Boolean
        Return false
    End Function
    
    Protected Overrides Sub ReadXmlSerializable(ByVal reader As XmlReader)
        Me.Reset
        Dim ds As DataSet = New DataSet
        ds.ReadXml(reader)
        If (Not (ds.Tables("dsProdAgeMetric")) Is Nothing) Then
            Me.Tables.Add(New dsProdAgeMetricDataTable(ds.Tables("dsProdAgeMetric")))
        End If
        Me.DataSetName = ds.DataSetName
        Me.Prefix = ds.Prefix
        Me.Namespace = ds.Namespace
        Me.Locale = ds.Locale
        Me.CaseSensitive = ds.CaseSensitive
        Me.EnforceConstraints = ds.EnforceConstraints
        Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
        Me.InitVars
    End Sub
    
    Protected Overrides Function GetSchemaSerializable() As System.Xml.Schema.XmlSchema
        Dim stream As System.IO.MemoryStream = New System.IO.MemoryStream
        Me.WriteXmlSchema(New XmlTextWriter(stream, Nothing))
        stream.Position = 0
        Return System.Xml.Schema.XmlSchema.Read(New XmlTextReader(stream), Nothing)
    End Function
    
    Friend Sub InitVars()
        Me.tabledsProdAgeMetric = CType(Me.Tables("dsProdAgeMetric"),dsProdAgeMetricDataTable)
        If (Not (Me.tabledsProdAgeMetric) Is Nothing) Then
            Me.tabledsProdAgeMetric.InitVars
        End If
    End Sub
    
    Private Sub InitClass()
        Me.DataSetName = "dsProdAgeMetric"
        Me.Prefix = ""
        Me.Namespace = "http://tempuri.org/dsProdAgeMetric.xsd"
        Me.Locale = New System.Globalization.CultureInfo("en-US")
        Me.CaseSensitive = false
        Me.EnforceConstraints = true
        Me.tabledsProdAgeMetric = New dsProdAgeMetricDataTable
        Me.Tables.Add(Me.tabledsProdAgeMetric)
    End Sub
    
    Private Function ShouldSerializedsProdAgeMetric() As Boolean
        Return false
    End Function
    
    Private Sub SchemaChanged(ByVal sender As Object, ByVal e As System.ComponentModel.CollectionChangeEventArgs)
        If (e.Action = System.ComponentModel.CollectionChangeAction.Remove) Then
            Me.InitVars
        End If
    End Sub
    
    Public Delegate Sub dsProdAgeMetricRowChangeEventHandler(ByVal sender As Object, ByVal e As dsProdAgeMetricRowChangeEvent)
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class dsProdAgeMetricDataTable
        Inherits DataTable
        Implements System.Collections.IEnumerable
        
        Private columnGROUPNAME As DataColumn
        
        Private columnAGE As DataColumn
        
        Friend Sub New()
            MyBase.New("dsProdAgeMetric")
            Me.InitClass
        End Sub
        
        Friend Sub New(ByVal table As DataTable)
            MyBase.New(table.TableName)
            If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
                Me.CaseSensitive = table.CaseSensitive
            End If
            If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
                Me.Locale = table.Locale
            End If
            If (table.Namespace <> table.DataSet.Namespace) Then
                Me.Namespace = table.Namespace
            End If
            Me.Prefix = table.Prefix
            Me.MinimumCapacity = table.MinimumCapacity
            Me.DisplayExpression = table.DisplayExpression
        End Sub
        
        <System.ComponentModel.Browsable(false)>  _
        Public ReadOnly Property Count As Integer
            Get
                Return Me.Rows.Count
            End Get
        End Property
        
        Friend ReadOnly Property GROUPNAMEColumn As DataColumn
            Get
                Return Me.columnGROUPNAME
            End Get
        End Property
        
        Friend ReadOnly Property AGEColumn As DataColumn
            Get
                Return Me.columnAGE
            End Get
        End Property
        
        Public Default ReadOnly Property Item(ByVal index As Integer) As dsProdAgeMetricRow
            Get
                Return CType(Me.Rows(index),dsProdAgeMetricRow)
            End Get
        End Property
        
        Public Event dsProdAgeMetricRowChanged As dsProdAgeMetricRowChangeEventHandler
        
        Public Event dsProdAgeMetricRowChanging As dsProdAgeMetricRowChangeEventHandler
        
        Public Event dsProdAgeMetricRowDeleted As dsProdAgeMetricRowChangeEventHandler
        
        Public Event dsProdAgeMetricRowDeleting As dsProdAgeMetricRowChangeEventHandler
        
        Public Overloads Sub AdddsProdAgeMetricRow(ByVal row As dsProdAgeMetricRow)
            Me.Rows.Add(row)
        End Sub
        
        Public Overloads Function AdddsProdAgeMetricRow(ByVal GROUPNAME As String, ByVal AGE As Decimal) As dsProdAgeMetricRow
            Dim rowdsProdAgeMetricRow As dsProdAgeMetricRow = CType(Me.NewRow,dsProdAgeMetricRow)
            rowdsProdAgeMetricRow.ItemArray = New Object() {GROUPNAME, AGE}
            Me.Rows.Add(rowdsProdAgeMetricRow)
            Return rowdsProdAgeMetricRow
        End Function
        
        Public Function GetEnumerator() As System.Collections.IEnumerator Implements System.Collections.IEnumerable.GetEnumerator
            Return Me.Rows.GetEnumerator
        End Function
        
        Public Overrides Function Clone() As DataTable
            Dim cln As dsProdAgeMetricDataTable = CType(MyBase.Clone,dsProdAgeMetricDataTable)
            cln.InitVars
            Return cln
        End Function
        
        Protected Overrides Function CreateInstance() As DataTable
            Return New dsProdAgeMetricDataTable
        End Function
        
        Friend Sub InitVars()
            Me.columnGROUPNAME = Me.Columns("GROUPNAME")
            Me.columnAGE = Me.Columns("AGE")
        End Sub
        
        Private Sub InitClass()
            Me.columnGROUPNAME = New DataColumn("GROUPNAME", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnGROUPNAME)
            Me.columnAGE = New DataColumn("AGE", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnAGE)
            Me.columnGROUPNAME.AllowDBNull = false
            Me.columnAGE.AllowDBNull = false
        End Sub
        
        Public Function NewdsProdAgeMetricRow() As dsProdAgeMetricRow
            Return CType(Me.NewRow,dsProdAgeMetricRow)
        End Function
        
        Protected Overrides Function NewRowFromBuilder(ByVal builder As DataRowBuilder) As DataRow
            Return New dsProdAgeMetricRow(builder)
        End Function
        
        Protected Overrides Function GetRowType() As System.Type
            Return GetType(dsProdAgeMetricRow)
        End Function
        
        Protected Overrides Sub OnRowChanged(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanged(e)
            If (Not (Me.dsProdAgeMetricRowChangedEvent) Is Nothing) Then
                RaiseEvent dsProdAgeMetricRowChanged(Me, New dsProdAgeMetricRowChangeEvent(CType(e.Row,dsProdAgeMetricRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowChanging(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanging(e)
            If (Not (Me.dsProdAgeMetricRowChangingEvent) Is Nothing) Then
                RaiseEvent dsProdAgeMetricRowChanging(Me, New dsProdAgeMetricRowChangeEvent(CType(e.Row,dsProdAgeMetricRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleted(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleted(e)
            If (Not (Me.dsProdAgeMetricRowDeletedEvent) Is Nothing) Then
                RaiseEvent dsProdAgeMetricRowDeleted(Me, New dsProdAgeMetricRowChangeEvent(CType(e.Row,dsProdAgeMetricRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleting(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleting(e)
            If (Not (Me.dsProdAgeMetricRowDeletingEvent) Is Nothing) Then
                RaiseEvent dsProdAgeMetricRowDeleting(Me, New dsProdAgeMetricRowChangeEvent(CType(e.Row,dsProdAgeMetricRow), e.Action))
            End If
        End Sub
        
        Public Sub RemovedsProdAgeMetricRow(ByVal row As dsProdAgeMetricRow)
            Me.Rows.Remove(row)
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class dsProdAgeMetricRow
        Inherits DataRow
        
        Private tabledsProdAgeMetric As dsProdAgeMetricDataTable
        
        Friend Sub New(ByVal rb As DataRowBuilder)
            MyBase.New(rb)
            Me.tabledsProdAgeMetric = CType(Me.Table,dsProdAgeMetricDataTable)
        End Sub
        
        Public Property GROUPNAME As String
            Get
                Return CType(Me(Me.tabledsProdAgeMetric.GROUPNAMEColumn),String)
            End Get
            Set
                Me(Me.tabledsProdAgeMetric.GROUPNAMEColumn) = value
            End Set
        End Property
        
        Public Property AGE As Decimal
            Get
                Return CType(Me(Me.tabledsProdAgeMetric.AGEColumn),Decimal)
            End Get
            Set
                Me(Me.tabledsProdAgeMetric.AGEColumn) = value
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class dsProdAgeMetricRowChangeEvent
        Inherits EventArgs
        
        Private eventRow As dsProdAgeMetricRow
        
        Private eventAction As DataRowAction
        
        Public Sub New(ByVal row As dsProdAgeMetricRow, ByVal action As DataRowAction)
            MyBase.New
            Me.eventRow = row
            Me.eventAction = action
        End Sub
        
        Public ReadOnly Property Row As dsProdAgeMetricRow
            Get
                Return Me.eventRow
            End Get
        End Property
        
        Public ReadOnly Property Action As DataRowAction
            Get
                Return Me.eventAction
            End Get
        End Property
    End Class
End Class
