'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.2032
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Data
Imports System.Runtime.Serialization
Imports System.Xml


<Serializable(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Diagnostics.DebuggerStepThrough(),  _
 System.ComponentModel.ToolboxItem(true)>  _
Public Class dsOcupation
    Inherits DataSet
    
    Private tabledsOcupation As dsOcupationDataTable
    
    Public Sub New()
        MyBase.New
        Me.InitClass
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    Protected Sub New(ByVal info As SerializationInfo, ByVal context As StreamingContext)
        MyBase.New
        Dim strSchema As String = CType(info.GetValue("XmlSchema", GetType(System.String)),String)
        If (Not (strSchema) Is Nothing) Then
            Dim ds As DataSet = New DataSet
            ds.ReadXmlSchema(New XmlTextReader(New System.IO.StringReader(strSchema)))
            If (Not (ds.Tables("dsOcupation")) Is Nothing) Then
                Me.Tables.Add(New dsOcupationDataTable(ds.Tables("dsOcupation")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.InitClass
        End If
        Me.GetSerializationData(info, context)
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    <System.ComponentModel.Browsable(false),  _
     System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)>  _
    Public ReadOnly Property dsOcupation As dsOcupationDataTable
        Get
            Return Me.tabledsOcupation
        End Get
    End Property
    
    Public Overrides Function Clone() As DataSet
        Dim cln As dsOcupation = CType(MyBase.Clone,dsOcupation)
        cln.InitVars
        Return cln
    End Function
    
    Protected Overrides Function ShouldSerializeTables() As Boolean
        Return false
    End Function
    
    Protected Overrides Function ShouldSerializeRelations() As Boolean
        Return false
    End Function
    
    Protected Overrides Sub ReadXmlSerializable(ByVal reader As XmlReader)
        Me.Reset
        Dim ds As DataSet = New DataSet
        ds.ReadXml(reader)
        If (Not (ds.Tables("dsOcupation")) Is Nothing) Then
            Me.Tables.Add(New dsOcupationDataTable(ds.Tables("dsOcupation")))
        End If
        Me.DataSetName = ds.DataSetName
        Me.Prefix = ds.Prefix
        Me.Namespace = ds.Namespace
        Me.Locale = ds.Locale
        Me.CaseSensitive = ds.CaseSensitive
        Me.EnforceConstraints = ds.EnforceConstraints
        Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
        Me.InitVars
    End Sub
    
    Protected Overrides Function GetSchemaSerializable() As System.Xml.Schema.XmlSchema
        Dim stream As System.IO.MemoryStream = New System.IO.MemoryStream
        Me.WriteXmlSchema(New XmlTextWriter(stream, Nothing))
        stream.Position = 0
        Return System.Xml.Schema.XmlSchema.Read(New XmlTextReader(stream), Nothing)
    End Function
    
    Friend Sub InitVars()
        Me.tabledsOcupation = CType(Me.Tables("dsOcupation"),dsOcupationDataTable)
        If (Not (Me.tabledsOcupation) Is Nothing) Then
            Me.tabledsOcupation.InitVars
        End If
    End Sub
    
    Private Sub InitClass()
        Me.DataSetName = "dsOcupation"
        Me.Prefix = ""
        Me.Namespace = "http://tempuri.org/dsOcupation.xsd"
        Me.Locale = New System.Globalization.CultureInfo("en-US")
        Me.CaseSensitive = false
        Me.EnforceConstraints = true
        Me.tabledsOcupation = New dsOcupationDataTable
        Me.Tables.Add(Me.tabledsOcupation)
    End Sub
    
    Private Function ShouldSerializedsOcupation() As Boolean
        Return false
    End Function
    
    Private Sub SchemaChanged(ByVal sender As Object, ByVal e As System.ComponentModel.CollectionChangeEventArgs)
        If (e.Action = System.ComponentModel.CollectionChangeAction.Remove) Then
            Me.InitVars
        End If
    End Sub
    
    Public Delegate Sub dsOcupationRowChangeEventHandler(ByVal sender As Object, ByVal e As dsOcupationRowChangeEvent)
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class dsOcupationDataTable
        Inherits DataTable
        Implements System.Collections.IEnumerable
        
        Private columnHIDDENVALUE1 As DataColumn
        
        Private columnFULLNAME As DataColumn
        
        Private columnQUANTITY As DataColumn
        
        Friend Sub New()
            MyBase.New("dsOcupation")
            Me.InitClass
        End Sub
        
        Friend Sub New(ByVal table As DataTable)
            MyBase.New(table.TableName)
            If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
                Me.CaseSensitive = table.CaseSensitive
            End If
            If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
                Me.Locale = table.Locale
            End If
            If (table.Namespace <> table.DataSet.Namespace) Then
                Me.Namespace = table.Namespace
            End If
            Me.Prefix = table.Prefix
            Me.MinimumCapacity = table.MinimumCapacity
            Me.DisplayExpression = table.DisplayExpression
        End Sub
        
        <System.ComponentModel.Browsable(false)>  _
        Public ReadOnly Property Count As Integer
            Get
                Return Me.Rows.Count
            End Get
        End Property
        
        Friend ReadOnly Property HIDDENVALUE1Column As DataColumn
            Get
                Return Me.columnHIDDENVALUE1
            End Get
        End Property
        
        Friend ReadOnly Property FULLNAMEColumn As DataColumn
            Get
                Return Me.columnFULLNAME
            End Get
        End Property
        
        Friend ReadOnly Property QUANTITYColumn As DataColumn
            Get
                Return Me.columnQUANTITY
            End Get
        End Property
        
        Public Default ReadOnly Property Item(ByVal index As Integer) As dsOcupationRow
            Get
                Return CType(Me.Rows(index),dsOcupationRow)
            End Get
        End Property
        
        Public Event dsOcupationRowChanged As dsOcupationRowChangeEventHandler
        
        Public Event dsOcupationRowChanging As dsOcupationRowChangeEventHandler
        
        Public Event dsOcupationRowDeleted As dsOcupationRowChangeEventHandler
        
        Public Event dsOcupationRowDeleting As dsOcupationRowChangeEventHandler
        
        Public Overloads Sub AdddsOcupationRow(ByVal row As dsOcupationRow)
            Me.Rows.Add(row)
        End Sub
        
        Public Overloads Function AdddsOcupationRow(ByVal HIDDENVALUE1 As String, ByVal FULLNAME As String, ByVal QUANTITY As Decimal) As dsOcupationRow
            Dim rowdsOcupationRow As dsOcupationRow = CType(Me.NewRow,dsOcupationRow)
            rowdsOcupationRow.ItemArray = New Object() {HIDDENVALUE1, FULLNAME, QUANTITY}
            Me.Rows.Add(rowdsOcupationRow)
            Return rowdsOcupationRow
        End Function
        
        Public Function GetEnumerator() As System.Collections.IEnumerator Implements System.Collections.IEnumerable.GetEnumerator
            Return Me.Rows.GetEnumerator
        End Function
        
        Public Overrides Function Clone() As DataTable
            Dim cln As dsOcupationDataTable = CType(MyBase.Clone,dsOcupationDataTable)
            cln.InitVars
            Return cln
        End Function
        
        Protected Overrides Function CreateInstance() As DataTable
            Return New dsOcupationDataTable
        End Function
        
        Friend Sub InitVars()
            Me.columnHIDDENVALUE1 = Me.Columns("HIDDENVALUE1")
            Me.columnFULLNAME = Me.Columns("FULLNAME")
            Me.columnQUANTITY = Me.Columns("QUANTITY")
        End Sub
        
        Private Sub InitClass()
            Me.columnHIDDENVALUE1 = New DataColumn("HIDDENVALUE1", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnHIDDENVALUE1)
            Me.columnFULLNAME = New DataColumn("FULLNAME", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnFULLNAME)
            Me.columnQUANTITY = New DataColumn("QUANTITY", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnQUANTITY)
            Me.columnHIDDENVALUE1.AllowDBNull = false
            Me.columnFULLNAME.AllowDBNull = false
            Me.columnQUANTITY.AllowDBNull = false
        End Sub
        
        Public Function NewdsOcupationRow() As dsOcupationRow
            Return CType(Me.NewRow,dsOcupationRow)
        End Function
        
        Protected Overrides Function NewRowFromBuilder(ByVal builder As DataRowBuilder) As DataRow
            Return New dsOcupationRow(builder)
        End Function
        
        Protected Overrides Function GetRowType() As System.Type
            Return GetType(dsOcupationRow)
        End Function
        
        Protected Overrides Sub OnRowChanged(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanged(e)
            If (Not (Me.dsOcupationRowChangedEvent) Is Nothing) Then
                RaiseEvent dsOcupationRowChanged(Me, New dsOcupationRowChangeEvent(CType(e.Row,dsOcupationRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowChanging(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanging(e)
            If (Not (Me.dsOcupationRowChangingEvent) Is Nothing) Then
                RaiseEvent dsOcupationRowChanging(Me, New dsOcupationRowChangeEvent(CType(e.Row,dsOcupationRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleted(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleted(e)
            If (Not (Me.dsOcupationRowDeletedEvent) Is Nothing) Then
                RaiseEvent dsOcupationRowDeleted(Me, New dsOcupationRowChangeEvent(CType(e.Row,dsOcupationRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleting(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleting(e)
            If (Not (Me.dsOcupationRowDeletingEvent) Is Nothing) Then
                RaiseEvent dsOcupationRowDeleting(Me, New dsOcupationRowChangeEvent(CType(e.Row,dsOcupationRow), e.Action))
            End If
        End Sub
        
        Public Sub RemovedsOcupationRow(ByVal row As dsOcupationRow)
            Me.Rows.Remove(row)
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class dsOcupationRow
        Inherits DataRow
        
        Private tabledsOcupation As dsOcupationDataTable
        
        Friend Sub New(ByVal rb As DataRowBuilder)
            MyBase.New(rb)
            Me.tabledsOcupation = CType(Me.Table,dsOcupationDataTable)
        End Sub
        
        Public Property HIDDENVALUE1 As String
            Get
                Return CType(Me(Me.tabledsOcupation.HIDDENVALUE1Column),String)
            End Get
            Set
                Me(Me.tabledsOcupation.HIDDENVALUE1Column) = value
            End Set
        End Property
        
        Public Property FULLNAME As String
            Get
                Return CType(Me(Me.tabledsOcupation.FULLNAMEColumn),String)
            End Get
            Set
                Me(Me.tabledsOcupation.FULLNAMEColumn) = value
            End Set
        End Property
        
        Public Property QUANTITY As Decimal
            Get
                Return CType(Me(Me.tabledsOcupation.QUANTITYColumn),Decimal)
            End Get
            Set
                Me(Me.tabledsOcupation.QUANTITYColumn) = value
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class dsOcupationRowChangeEvent
        Inherits EventArgs
        
        Private eventRow As dsOcupationRow
        
        Private eventAction As DataRowAction
        
        Public Sub New(ByVal row As dsOcupationRow, ByVal action As DataRowAction)
            MyBase.New
            Me.eventRow = row
            Me.eventAction = action
        End Sub
        
        Public ReadOnly Property Row As dsOcupationRow
            Get
                Return Me.eventRow
            End Get
        End Property
        
        Public ReadOnly Property Action As DataRowAction
            Get
                Return Me.eventAction
            End Get
        End Property
    End Class
End Class
